export const exampleProfiles = [
    {
        pageContent:
            "I'm Julia, a 30-year-old User Experience Designer who enjoys the creative challenges of tech with the human-centered focus of design. Having grown up in a bilingual household, I adore cultural exchanges and language learning. My free time is often filled with outdoor activities, yoga, and my favorite pastime, salsa dancing. I'm a foodie at heart, and while I must stick to a gluten-free diet, I love exploring Austin's food scene. My liberal views are a big part of who I am, as is my spiritual but down-to-earth approach to life. I cherish my close-knit family and look forward to building my own. Finding someone with a blend of ambition and the ability to unwind and enjoy the simple things in life would be my ideal match. Looking for someone who is kind, intelligent, and has a great sense of humor. He should be curious about the world, respectful towards different cultures, and open to exploring new experiences together. Being active and valuing a healthy lifestyle is important, but he should also be ready for lazy Sunday brunches. A strong connection to family and a supportive nature are qualities that would complement me well.",
        metadata: {
            activitiesIEnjoy: [Array],
            age: 30,
            attachmentStyle: 'Secure',
            attractivenessScore: 7,
            birthDateDay: 15,
            birthDateMonth: 8,
            birthDateYear: 1992,
            birthdate: 8,
            bodyType: 'Athletic',
            celebrityCrush: [Array],
            profileImageUrls: ['1.png', '2.png'],
            churchAttendance: 'Occasionally',
            city: 'Austin',
            company: 'Dell Technologies',
            covidVaccinated: true,
            createdAt: 1698743755570,

            datingIntentions: 'Relationship',
            describeYourHome:
                'Cozy 1-bedroom apartment with a balcony and a view of the Greenbelt',
            describeYourIdealFirstDate:
                'A picnic in Zilker Park followed by a casual walk with ice cream and engaging conversation',
            describeYourIdealPartner: [Array],
            describeYourSelfInYourOwnWords: [Array],
            dietaryRestrictions: 'Gluten-Free',
            doYouOwnYourHome: false,
            doYouSmoke: 'No',
            drinkingHabits: 'Socially',
            ethnicity: 'Hispanic/Latino',
            eyeColor: 'Green',
            faith: 'Spiritual but not religious',
            favoriteBars: [Array],
            favoriteRestaurants: [Array],
            firestoreId: 'nnjHSouRvL1CeO2GXFbt',
            firstName: 'Julia',
            gender: 'Female',
            haircolor: 'Black',
            hasChildren: false,
            hasKids: false,
            hasPets: false,
            hasStartedOnboarding: true,
            height: 5,
            heightInInches: 67,
            highestEducationLevelCompleted: "Master's Degree",
            id: 'k107bax1qfawszasmmej7p',
            idVerified: true,
            income: 87000,
            incomeVerified: true,
            industry: 'Technology',
            introductionDescription: [Array],
            isOnboarding: false,
            lastLogin: 1698746758570,
            lastName: 'Ramirez',
            latitutide: 30.2672,
            longitude: -97.7431,
            myersBriggs: 'INFJ',
            neighborhood: 'South Congress',
            numberOfPets: 0,
            occupation: 'User Experience Designer',
            onboarded: true,
            onboardingProgess: 100,
            pineconeId: 'k107bax1qfawszasmmej7p',
            politicalAffiliation: 'Liberal',
            preferredAgeMax: 35,
            preferredAgeMin: 28,
            preferredBodyType: [Array],
            preferredChurchAttendance: 'Occasionally',
            preferredCovidVaccinated: true,
            preferredDatingIntentions: 'Relationship',
            preferredDrinkingHabits: [Array],
            preferredEducationLevel: [Array],
            preferredEthnicities: [Array],
            preferredFaith: [Array],
            preferredGender: 'Male',
            preferredIncomeMax: 150000,
            preferredIncomeMin: 60000,
            preferredMaxHeight: 76,
            preferredMethodOfFirstContact: 'Text message',
            preferredMinHeight: 68,
            preferredPoliticalAffiliation: [Array],
            preferredQualitiesInYourIdealPartner: [Array],
            preferredRelationshipStatus: [Array],
            preferredSexualOrientation: [Array],
            profileImageUrls: ['1.png', '2.png'],
            relationshipStatus: 'Never Married',
            rentOrOwn: 'Rent',
            sexualOrientation: 'Straight',
            sober: false,
            state: 'TX',
            synthetic: true,
            syntheticProfileVersion: 1,
            wantsChildren: 'Yes',
            zipcode: 78704,
        },
    },
    {
        pageContent:
            "I'm Julia, a 27-year-old marketing coordinator who loves the vibrant culture of Austin. I'm passionate about my career but also value balance through yoga, paddle boarding, and exploring the city's diverse culinary scene. I'm looking for meaningful connections and a partner to share in life's adventures. I'm looking for a man with intelligence and integrity, who values personal growth and emotional connection. Being physically active and having a sense of adventure is important, as well as enjoying the simple joys of life, including a passion for food and culture.",
        metadata: {
            activitiesIEnjoy: [Array],
            age: 27,
            attachmentStyle: 'Secure',
            birthDateDay: 15,
            birthDateMonth: 7,
            birthDateYear: 1995,
            birthdate: 7,
            bodyType: 'Fit',
            city: 'Austin',
            company: 'Whole Foods Market',
            covidVaccinated: true,
            createdAt: 1698743755570,
            datingIntentions: 'Relationship',
            describeYourIdealPartner: [Array],
            describeYourSelfInYourOwnWords: [Array],
            dietaryRestrictions: 'None',
            doYouOwnYourHome: false,
            doesSmoke: 'No',
            drinkingHabits: 'Socially',
            ethnicity: 'Hispanic/Latino',
            eyeColor: 'Green',
            faith: 'Spiritual but not religious',
            favoriteBars: [Array],
            favoriteRestaurants: [Array],
            firestoreId: 'uYn2FSwTkO0YE9CitPpm',
            firstName: 'Julia',
            gender: 'Female',
            haircolor: 'Black',
            hasChildren: false,
            hasPets: false,
            hasStartedOnboarding: true,
            height: 5,
            heightInInches: 66,
            highestEducationLevelCompleted: "Bachelor's Degree",
            id: 4,
            idVerified: true,
            income: 58000,
            industry: 'Marketing and Advertising',
            introductionDescription: [Array],
            isOnboarding: false,
            lastLogin: 1698746758570,
            lastName: 'Hernandez',
            latitutide: 30.2672,
            longitude: -97.7431,
            neighborhood: 'South Congress',
            occupation: 'Marketing Coordinator',
            onboarded: true,
            onboardingProgess: 100,
            pineconeId: 4,
            politicalAffiliation: 'Moderate',
            profileImageUrls: ['1.png', '2.png'],
            relationshipStatus: 'Never Married',
            rentOrOwn: 'Rent',
            sexualOrientation: 'Straight',
            sober: false,
            state: 'TX',
            synthetic: true,
            syntheticProfileVersion: 1,
            wantsChildren: 'Yes',
            zipcode: 78704,
        },
    },
    {
        pageContent:
            "I'm Emily, a 24-year-old Elementary School Teacher. I'm passionate about shaping young minds and enjoy the little things in life like a good book or homemade pastry. I'm health-conscious, love being active outdoors, and I volunteer in my free time. Austin's vibrant atmosphere inspires my creativity, especially in my hobby of making short films. Politically, I'm liberal and inclined towards spirituality over organized religion. My ideal partner is someone who values education and personal growth, has a kind heart, and enjoys the outdoors. He's mature, has a stable career, and is ready for a serious relationship. I appreciate a man who is respectful, supportive, and shares my values on maintaining a healthy lifestyle.",
        metadata: {
            activitiesIEnjoy: [Array],
            age: 24,
            attachmentStyle: 'Secure',
            attractivenessScore: 7,
            birthDateDay: 15,
            birthDateMonth: 4,
            birthDateYear: 1998,
            birthdate: 4,
            bodyType: 'Athletic',
            celebrityCrush: 'Chris Hemsworth',
            churchAttendance: 'Occasionally',
            city: 'Austin',
            company: 'Austin Independent School District',
            covidVaccinated: true,
            createdAt: 1698765432100,
            dalìPrompt: [Array],
            datingIntentions: 'Relationship',
            describeYourHome: [Array],
            describeYourIdealFirstDate:
                'A casual meet-up at a coffee shop followed by a walk in the park',
            describeYourIdealPartner: [Array],
            describeYourSelfInYourOwnWords: [Array],
            dietaryRestrictions: 'Vegetarian',
            doYouOwnYourHome: false,
            doYouSmoke: 'No',
            drinkingHabits: 'Socially',
            ethnicity: 'Caucasian',
            eyeColor: 'Brown',
            faith: 'Spiritual but not religious',
            favoriteBars: [Array],
            favoriteRestaurants: [Array],
            firestoreId: 'RCbD8ilQuWK5kJd85LjS',
            firstName: 'Emily',
            gender: 'Female',
            hairColor: 'Blonde',
            hasChildren: false,
            hasPets: false,
            hasStartedOnboarding: true,
            height: 5,
            heightInInches: 66,
            highestEducationLevelCompleted: "Bachelor's Degree",
            id: 5,
            idVerified: true,
            income: 45000,
            incomeVerified: false,
            industry: 'Education',
            introductionDescription: [Array],
            isOnboarding: false,
            lastLogin: 1698768430000,
            lastName: 'Carter',
            latitutide: 30.2672,
            longitude: -97.7431,
            myersBriggs: 'ENFJ',
            neighborhood: 'South Congress',
            numberOfPets: 0,
            occupation: 'Elementary School Teacher',
            onboarded: true,
            onboardingProgess: 100,
            pineconeId: 5,
            politicalAffiliation: 'Liberal',
            preferredAgeMax: 30,
            preferredAgeMin: 26,
            preferredBodyType: [Array],
            preferredChurchAttendance: [Array],
            preferredCovidVaccinated: true,
            preferredDatingIntentions: 'Relationship',
            preferredDrinkingHabits: [Array],
            preferredEducationLevel: [Array],
            preferredEthnicities: [Array],
            preferredFaith: [Array],
            preferredGender: 'Male',
            preferredIncomeMax: 100000,
            preferredIncomeMin: 50000,
            preferredMaxHeight: 76,
            preferredMethodOfFirstContact: 'Text message',
            preferredMinHeight: 68,
            preferredPoliticalAffiliation: [Array],
            preferredQualitiesInYourIdealPartner: [Array],
            preferredRelationshipStatus: 'Never Married',
            preferredSexualOrientation: 'Straight',
            profileImageUrls: ['1.png', '2.png'],
            relationshipStatus: 'Never Married',
            rentOrOwn: 'Rent',
            sexualOrientation: 'Straight',
            sober: false,
            state: 'TX',
            synthetic: true,
            syntheticProfileVersion: 1,
            wantsChildren: 'Yes',
            zipcode: 78704,
        },
    },
    {
        pageContent:
            "Hi, I'm Samantha! A vibrant 30-year-old who loves her career in technology marketing. I'm a fitness enthusiast and passionate about clean eating. You'll often find me exploring the local trails or attending a yoga class. I'm a bit of a foodie and enjoy experimenting with new recipes, especially seafood. My ideal weekend involves catching a live show or trying a new restaurant. Politically, I lean towards liberal ideals and prefer someone with a similar outlook for meaningful discussions. I'm spiritual, cherishing a sense of connection with the universe more than following a specific religion. I'm excited to meet someone who shares my interests and values. I'm seeking a partner who is kind, confident, and has a passion for life. Someone who enjoys a mix of outdoor adventures and cozy nights in, values emotional intelligence, and is ready for a committed relationship.",
        metadata: {
            activitiesIEnjoy: [Array],
            age: 30,
            attachmentStyle: 'Secure',
            attractivenessScore: 7,
            birthDateDay: 17,
            birthDateMonth: 4,
            birthDateYear: 1992,
            birthdate: 4,
            bodyType: 'Athletic',
            celebrityCrush: [Array],
            churchAttendance: 'Occasionally',
            city: 'Austin',
            company: 'Dell Technologies',
            covidVaccinated: true,
            createdAt: 1699973056570,
            dalìPrompt: [Array],
            datingIntentions: 'Relationship',
            describeYourHome:
                'Cozy and well-decorated one-bedroom apartment in a vibrant neighborhood',
            describeYourIdealFirstDate: [Array],
            describeYourIdealPartner: [Array],
            describeYourSelfInYourOwnWords: [Array],
            dietaryRestrictions: 'Pescatarian',
            doYouOwnYourHome: false,
            doYouSmoke: 'No',
            drinkingHabits: 'Socially',
            ethnicity: 'Caucasian',
            eyeColor: 'Green',
            faith: 'Spiritual but not religious',
            favoriteBars: [Array],
            favoriteRestaurants: [Array],
            firstName: 'Samantha',
            gender: 'Female',
            haircolor: 'Blonde',
            hasChildren: false,
            hasPets: false,
            height: 5,
            heightInInches: 66,
            highestEducationLevelCompleted: "Master's Degree",
            id: 'qcxh94bufnxsajdfu84',
            idVerified: true,
            income: 65000,
            incomeVerified: false,
            industry: 'Technology',
            introductionDescription: [Array],
            lastLogin: 1700076658570,
            lastName: 'Carter',
            latitutide: 30.2672,
            longitude: -97.7431,
            myersBriggs: 'ENFJ',
            neighborhood: 'South Congress',
            occupation: 'Marketing Coordinator',
            politicalAffiliation: 'Liberal',
            preferredAgeMax: 35,
            preferredAgeMin: 28,
            preferredBodyType: [Array],
            preferredChurchAttendance: [Array],
            preferredCovidVaccinated: true,
            preferredDatingIntentions: 'Relationship',
            preferredDrinkingHabits: 'Light',
            preferredEducationLevel: [Array],
            preferredEthnicities: [Array],
            preferredFaith: [Array],
            preferredGender: 'Male',
            preferredIncomeMax: 150000,
            preferredIncomeMin: 50000,
            preferredMaxHeight: 76,
            preferredMethodOfFirstContact: 'Text message',
            preferredMinHeight: 68,
            preferredPoliticalAffiliation: [Array],
            preferredQualitiesInYourIdealPartner: [Array],
            preferredRelationshipStatus: [Array],
            preferredSexualOrientation: [Array],
            profileImageUrls: ['1.png', '2.png'],
            relationshipStatus: 'Never Married',
            rentOrOwn: 'Rent',
            sexualOrientation: 'Straight',
            sober: false,
            state: 'TX',
            synthetic: true,
            syntheticProfileVersion: 1,
            wantsChildren: 'Yes',
        },
    },
]